### ISSUE TITLE
aarch64

### ISSUE THREAD

**Issue by poetaster** [LouJo/SailDBMeter#2]
Hi, I've built it for you from my fork and added chum meta crediting you and linking back here. Let me know if this is ok:

https://build.sailfishos.org/package/show/sailfishos:chum:testing/SailDBMeter

Currently Meta is:

```
PackageName: SailDBMeter
Type: desktop-application
Categories:
 - Audio
 - Utility
DeveloperName: LouJou
PackagerName: Mark Washeim (poetaster)
Custom:
 - Repo: https://github.com/LouJou/SailDBMeter
 - PackagingRepo: https://github.com/poetaster/SailDBMeter
Icon: https://raw.githubusercontent.com/poetaster/SailDBMeter/master/harbour-saildbmeter.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/SailDBMeter/master/screenshots/20151225190436.png
 - https://raw.githubusercontent.com/poetaster/SailDBMeter/master/screenshots/20151225190436.png
Url:
 - HomePage: http://legolas.vefblog.net
```
